using Npgsql;

namespace Jellyfin.HotCache.Worker;

/// <summary>PostgreSQL implementation using row locks and expiring worker leases.</summary>
public sealed class PostgreSqlHotCacheJobStore(NpgsqlDataSource dataSource) : IHotCacheJobStore
{
    public async Task<HotCacheJob?> ClaimAsync(string workerId, TimeSpan leaseDuration, CancellationToken ct)
    {
        const string sql = """
            WITH next AS (SELECT id FROM hot_cache_jobs WHERE state = 'pending' OR (state = 'running' AND lease_expires_at < now()) ORDER BY priority DESC, created_at FOR UPDATE SKIP LOCKED LIMIT 1)
            UPDATE hot_cache_jobs j SET state='running', lease_owner=@owner, lease_expires_at=now() + @lease, attempts=j.attempts+1, updated_at=now() FROM next WHERE j.id=next.id
            RETURNING j.id,j.kind,j.canonical_path,j.hot_path,j.source_length,j.source_modified_utc,j.priority,j.is_active,j.is_pinned,j.is_copying,j.last_access_utc,j.attempts;
            """;
        await using var command = dataSource.CreateCommand(sql); command.Parameters.AddWithValue("owner", workerId); command.Parameters.AddWithValue("lease", leaseDuration);
        await using var reader = await command.ExecuteReaderAsync(ct).ConfigureAwait(false); return await reader.ReadAsync(ct).ConfigureAwait(false) ? Read(reader) : null;
    }
    public Task<bool> RenewAsync(Guid id, string owner, TimeSpan lease, CancellationToken ct) => ExecuteOwnedAsync("UPDATE hot_cache_jobs SET lease_expires_at=now()+@lease,updated_at=now() WHERE id=@id AND lease_owner=@owner AND lease_expires_at>now()", id, owner, ct, ("lease", lease));
    public Task ProgressAsync(Guid id, string owner, long bytes, CancellationToken ct) => ExecuteOwnedAsync("UPDATE hot_cache_jobs SET bytes_copied=@bytes,updated_at=now() WHERE id=@id AND lease_owner=@owner AND lease_expires_at>now()", id, owner, ct, ("bytes", bytes));
    public Task CompleteAsync(Guid id, string owner, string? hotPath, CancellationToken ct) => ExecuteOwnedAsync("UPDATE hot_cache_jobs SET state='completed',is_copying=false,hot_path=COALESCE(@hotPath,hot_path),lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=@id AND lease_owner=@owner AND lease_expires_at>now()", id, owner, ct, ("hotPath", (object?)hotPath ?? DBNull.Value));
    public Task FailAsync(Guid id, string owner, string error, CancellationToken ct) => ExecuteOwnedAsync("UPDATE hot_cache_jobs SET state=CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'pending' END,is_copying=false,last_error=@error,lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=@id AND lease_owner=@owner", id, owner, ct, ("error", error));
    public async Task<HotCacheJob?> ClaimEvictionAsync(string workerId, TimeSpan leaseDuration, CancellationToken ct)
    { const string sql = "WITH next AS (SELECT id FROM hot_cache_jobs WHERE state='completed' AND hot_path IS NOT NULL AND NOT is_active AND NOT is_pinned AND NOT is_copying AND priority <= 0 ORDER BY last_access_utc FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE hot_cache_jobs j SET kind='eviction',state='running',is_copying=true,lease_owner=@owner,lease_expires_at=now()+@lease,attempts=j.attempts+1,updated_at=now() FROM next WHERE j.id=next.id RETURNING j.id,j.kind,j.canonical_path,j.hot_path,j.source_length,j.source_modified_utc,j.priority,j.is_active,j.is_pinned,j.is_copying,j.last_access_utc,j.attempts;"; await using var cmd=dataSource.CreateCommand(sql); cmd.Parameters.AddWithValue("owner",workerId);cmd.Parameters.AddWithValue("lease",leaseDuration);await using var r=await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);return await r.ReadAsync(ct).ConfigureAwait(false)?Read(r):null; }
    public Task<bool> CanEvictAsync(Guid id, string owner, CancellationToken ct) => ExecuteOwnedAsync("UPDATE hot_cache_jobs SET updated_at=now() WHERE id=@id AND state='running' AND lease_owner=@owner AND lease_expires_at>now() AND NOT is_active AND NOT is_pinned AND priority<=0", id, owner, ct);
    public async Task<HotCacheQueueSnapshot> SnapshotAsync(CancellationToken ct)
    { const string sql="WITH retained AS (DELETE FROM hot_cache_events WHERE created_at < now() - interval '30 days' RETURNING id) SELECT count(*) FILTER (WHERE state IN ('pending','running')), COALESCE(EXTRACT(EPOCH FROM now()-min(created_at) FILTER (WHERE state IN ('pending','running'))),0), COALESCE(EXTRACT(EPOCH FROM now()-min(updated_at) FILTER (WHERE state='running' AND lease_expires_at>now())),0), pg_total_relation_size('hot_cache_events') + pg_total_relation_size('hot_cache_jobs'), (SELECT count(*) FROM hot_cache_events), (SELECT count(*) FROM hot_cache_events WHERE kind='validate-or-repair' AND detail='hot-miss' AND created_at > now() - interval '15 minutes'), (SELECT count(*) FROM hot_cache_events WHERE kind='validate-or-repair' AND detail <> 'hot-miss' AND created_at > now() - interval '15 minutes') FROM hot_cache_jobs"; await using var cmd=dataSource.CreateCommand(sql); await using var r=await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false); await r.ReadAsync(ct).ConfigureAwait(false); return new(r.GetInt64(0), TimeSpan.FromSeconds(r.GetDouble(1)), TimeSpan.FromSeconds(r.GetDouble(2)), r.GetInt64(3), r.GetInt64(4), r.GetInt64(5), r.GetInt64(6)); }
    public async Task ObserveBackendAsync(string backend, bool healthy, long totalBytes, long availableBytes, CancellationToken ct)
    { await using var cmd = dataSource.CreateCommand("INSERT INTO hot_cache_backend_observations(backend,mounted,healthy,total_bytes,used_bytes,available_bytes,observed_at) VALUES(@backend,true,@healthy,@total,@used,@available,now()) ON CONFLICT(backend) DO UPDATE SET mounted=excluded.mounted,healthy=excluded.healthy,total_bytes=excluded.total_bytes,used_bytes=excluded.used_bytes,available_bytes=excluded.available_bytes,observed_at=excluded.observed_at"); cmd.Parameters.AddWithValue("backend", backend); cmd.Parameters.AddWithValue("healthy", healthy); cmd.Parameters.AddWithValue("total", totalBytes); cmd.Parameters.AddWithValue("used", Math.Max(0, totalBytes - availableBytes)); cmd.Parameters.AddWithValue("available", availableBytes); await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false); }
    public async Task EventAsync(Guid id, string kind, string detail, CancellationToken ct) { await using var cmd = dataSource.CreateCommand("INSERT INTO hot_cache_events(job_id,kind,detail) VALUES(@id,@kind,@detail)"); cmd.Parameters.AddWithValue("id", id); cmd.Parameters.AddWithValue("kind", kind); cmd.Parameters.AddWithValue("detail", detail); await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false); }
    private async Task<bool> ExecuteOwnedAsync(string sql, Guid id, string owner, CancellationToken ct, params (string Name, object Value)[] values) { await using var cmd = dataSource.CreateCommand(sql); cmd.Parameters.AddWithValue("id", id); cmd.Parameters.AddWithValue("owner", owner); foreach (var value in values) cmd.Parameters.AddWithValue(value.Name, value.Value); return await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false) == 1; }
    private static HotCacheJob Read(NpgsqlDataReader r) => new(r.GetGuid(0), Enum.Parse<HotCacheJobKind>(r.GetString(1), true), r.GetString(2), r.IsDBNull(3) ? null : r.GetString(3), r.GetInt64(4), r.GetDateTime(5), r.GetInt32(6), r.GetBoolean(7), r.GetBoolean(8), r.GetBoolean(9), r.GetDateTime(10), r.GetInt32(11));
}
