using Jellyfin.HotCache.Worker;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

namespace Jellyfin.HotCache.Worker.Tests;

public sealed class HotCacheWorkerTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "hot-cache-tests-" + Guid.NewGuid());
    public HotCacheWorkerTests() { Directory.CreateDirectory(Path.Combine(_root, "cold")); Directory.CreateDirectory(Path.Combine(_root, "hot")); }
    [Fact] public async Task ProcessDeathMidCopy_FailsAndLeavesNoPartial()
    { var job = Promotion("video.bin", "abc"); var files = new TestFiles { ThrowDuringCopy = true }; var store = new Store(job); await Worker(store, files).ExecuteOnceAsync("one", default); Assert.Equal(1, store.Failures); Assert.Empty(Directory.EnumerateFiles(Path.Combine(_root, "hot"), "*.partial", SearchOption.AllDirectories)); }
    [Fact] public async Task LeaseExpiry_AllowsAnotherWorkerToClaim()
    { var store = new Store(Promotion("video.bin", "abc")) { LeaseExpired = true }; Assert.NotNull(await store.ClaimAsync("one", TimeSpan.FromMinutes(1), default)); Assert.NotNull(await store.ClaimAsync("two", TimeSpan.FromMinutes(1), default)); }
    [Fact] public async Task DuplicateWorkers_OnlyOneClaimsLiveLease()
    { var store = new Store(Promotion("video.bin", "abc")); Assert.NotNull(await store.ClaimAsync("one", TimeSpan.FromMinutes(1), default)); Assert.Null(await store.ClaimAsync("two", TimeSpan.FromMinutes(1), default)); }
    [Fact] public async Task FullFilesystem_FailsToColdWithoutPublish()
    { var store = new Store(Promotion("video.bin", "abc")); await Worker(store, new TestFiles { ThrowDuringCopy = true }).ExecuteOnceAsync("one", default); Assert.Equal(1, store.Failures); Assert.False(File.Exists(Path.Combine(_root, "hot", "video.bin"))); }
    [Fact] public async Task SourceMutation_DuringCopyDoesNotPublish()
    { var store = new Store(Promotion("video.bin", "abc")); var files = new TestFiles { MutateSource = Path.Combine(_root, "cold", "video.bin") }; await Worker(store, files).ExecuteOnceAsync("one", default); Assert.Equal(1, store.Failures); Assert.False(File.Exists(Path.Combine(_root, "hot", "video.bin"))); }
    [Fact] public async Task MountLoss_FailsToCold()
    { var store = new Store(Promotion("video.bin", "abc")); await Worker(store, new TestFiles { ThrowOnInfo = true }).ExecuteOnceAsync("one", default); Assert.Equal(1, store.Failures); }
    [Fact] public async Task LongCopy_RenewsLeaseWithoutBlockingProgress()
    { var store = new Store(Promotion("video.bin", new string('x', 2_000_000))); await Worker(store, new TestFiles(), TimeSpan.FromTicks(1)).ExecuteOnceAsync("one", default); Assert.True(store.Renewals > 1); }
    [Fact] public async Task Eviction_IsIdempotentAndProtectsPinned()
    { File.WriteAllText(Path.Combine(_root, "hot", "old.bin"), "x"); var job = new HotCacheJob(Guid.NewGuid(), HotCacheJobKind.Eviction, "", Path.Combine(_root, "hot", "old.bin"), 0, DateTime.UtcNow, 0, false, false, false, DateTime.UtcNow.AddDays(-1), 0); var store = new Store(job); var worker=Worker(store,new TestFiles()); await worker.ExecuteOnceAsync("one",default); await worker.ExecuteOnceAsync("two",default); Assert.False(File.Exists(Path.Combine(_root,"hot","old.bin"))); }
    [Fact] public async Task CapacityEviction_UsesLruAndCleansAbandonedPartials()
    { var old=Path.Combine(_root,"hot","old.bin"); File.WriteAllText(old,"x"); var partial=Path.Combine(_root,"hot",".dead.partial"); File.WriteAllText(partial,"x"); File.SetLastWriteTimeUtc(partial,DateTime.UtcNow.AddHours(-2)); var e=new HotCacheJob(Guid.NewGuid(),HotCacheJobKind.Eviction,"",old,0,DateTime.UtcNow,0,false,false,false,DateTime.UtcNow.AddDays(-1),0); var store=new Store(null){ Candidates=[e] }; await Worker(store,new TestFiles{ Available=0, Total=100 }).ExecuteOnceAsync("one",default); Assert.False(File.Exists(old)); Assert.False(File.Exists(partial)); }
    private HotCacheJob Promotion(string name,string content) { var source=Path.Combine(_root,"cold",name); File.WriteAllText(source,content); var info=new FileInfo(source); return new(Guid.NewGuid(),HotCacheJobKind.Promotion,source,null,info.Length,info.LastWriteTimeUtc,0,false,false,false,DateTime.UtcNow,0); }
    private HotCacheWorker Worker(Store store, TestFiles files, TimeSpan? leaseDuration = null) => new(store, files, new HotCacheOptions { CanonicalRoot=Path.Combine(_root,"cold"), HotRoot=Path.Combine(_root,"hot"), HighWatermark=.5, LowWatermark=.1, PartialFileMaxAge=TimeSpan.FromHours(1), LeaseDuration=leaseDuration ?? TimeSpan.FromMinutes(2) }, NullLogger<HotCacheWorker>.Instance);
    public void Dispose() { Directory.Delete(_root, true); }
    private sealed class Store(HotCacheJob? next) : IHotCacheJobStore { private HotCacheJob? _next=next; public bool LeaseExpired; public int Failures; public int Renewals; public List<HotCacheJob> Candidates { get; set; }=[]; public Task<HotCacheJob?> ClaimAsync(string workerId,TimeSpan leaseDuration,CancellationToken c) { if(_next is null)return Task.FromResult<HotCacheJob?>(null); if(!LeaseExpired && _next.Attempts>0)return Task.FromResult<HotCacheJob?>(null); _next=_next with { Attempts=_next.Attempts+1}; return Task.FromResult<HotCacheJob?>(_next); } public Task<bool> RenewAsync(Guid a,string b,TimeSpan c,CancellationToken d){Renewals++;return Task.FromResult(true);} public Task ProgressAsync(Guid a,string b,long c,CancellationToken d)=>Task.CompletedTask; public Task CompleteAsync(Guid a,string b,CancellationToken c){_next=null;return Task.CompletedTask;} public Task FailAsync(Guid a,string b,string c,CancellationToken d){Failures++;_next=null;return Task.CompletedTask;} public Task<IReadOnlyList<HotCacheJob>> EvictionCandidatesAsync(CancellationToken c)=>Task.FromResult<IReadOnlyList<HotCacheJob>>(Candidates); public Task EventAsync(Guid a,string b,string c,CancellationToken d)=>Task.CompletedTask; }
    private sealed class TestFiles : IFileOperations { private readonly PhysicalFileOperations _inner=new(); public bool ThrowDuringCopy; public bool ThrowOnInfo; public string? MutateSource; public long Available=100; public long Total=100; public long GetAvailableSpace(string p)=>Available; public long GetTotalSpace(string p)=>Total; public bool FileExists(string p)=>_inner.FileExists(p); public FileInfo GetFileInfo(string p){if(ThrowOnInfo)throw new IOException("mount lost");return _inner.GetFileInfo(p);} public IEnumerable<string> EnumerateFiles(string r,string p)=>_inner.EnumerateFiles(r,p); public void CreateDirectory(string p)=>_inner.CreateDirectory(p); public async Task CopyAsync(string s,string d,Func<long,CancellationToken,Task> p,CancellationToken c){if(ThrowDuringCopy)throw new IOException("full filesystem");await _inner.CopyAsync(s,d,p,c);if(MutateSource is not null)File.AppendAllText(MutateSource,"!");} public void MoveNoReplace(string s,string d)=>_inner.MoveNoReplace(s,d); public void Delete(string p)=>_inner.Delete(p); }
}
